image:
  file: gitpod.dockerfile
ports:
 - port: 8082
tasks:
 - init: >
  mongod --dbpath /workspace/data --fork --logpath /workspace/log &&
  git clone https://github.com/jjpera/estudo-spring-historico.git /workspace/dependence
 
