/*
 * LinhaGo
 *
 * Controle de Linha Telefonica
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TipoHistorico string

// List of TipoHistorico
const (
	POST TipoHistorico = "post"
	PUT TipoHistorico = "put"
	DELETE TipoHistorico = "delete"
	GET TipoHistorico = "get"
)
