/*
 * LinhaGo
 *
 * Controle de Linha Telefonica
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Sistema string

// List of Sistema
const (
	LINHA Sistema = "linha"
	BANDA Sistema = "banda"
	TV Sistema = "tv"
	HISTORICO Sistema = "historico"
)
