/*
 * LinhaGo
 *
 * Controle de Linha Telefonica
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Historico struct {

	Id int64 `json:"id,omitempty"`

	Data time.Time `json:"data,omitempty"`

	Tipo *TipoHistorico `json:"tipo,omitempty"`

	Sistema *Sistema `json:"sistema,omitempty"`

	Descricao string `json:"descricao,omitempty"`
}
