/*
 * LinhaGo
 *
 * Controle de Linha Telefonica
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Retorno struct {

	Codigo int64 `json:"codigo,omitempty"`

	Descricao string `json:"descricao,omitempty"`

	Registros int32 `json:"registros,omitempty"`

	Pagina int32 `json:"pagina,omitempty"`

	QtdePagina int32 `json:"qtdePagina,omitempty"`
}
