/*
 * LinhaGo
 *
 * Controle de Linha Telefonica
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Linha struct {

	Id int64 `json:"id,omitempty"`

	Ddd string `json:"ddd,omitempty"`

	Numero string `json:"numero,omitempty"`
}
